server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: "default"

topic:
  names:
    CANCEL: t.cancel
    PROCESS: t.process
    UPDATE: t.update

com:
  github:
    blog:
      jwtSecret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      jwtExpirationMs: 1800000