CREATE TABLE IF NOT EXISTS blogging_platform.post (
    post_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id      bigint      NOT NULL,
    title        text        NOT NULL,
    content      text        NOT NULL,
    published_at timestamptz NOT NULL
);

ALTER TABLE IF EXISTS blogging_platform.post
ADD CONSTRAINT post_pk PRIMARY KEY (post_id);

ALTER TABLE IF EXISTS blogging_platform.post
ADD CONSTRAINT post_fk FOREIGN KEY (user_id) REFERENCES blogging_platform.user(user_id) ON DELETE SET NULL;