CREATE TABLE IF NOT EXISTS blogging_platform.reaction (
    reaction_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    reaction_name text NOT NULL
);

ALTER TABLE IF EXISTS blogging_platform.reaction
ADD CONSTRAINT reaction_pkey PRIMARY KEY (reaction_id);

CREATE UNIQUE INDEX reaction_reaction_name_key ON blogging_platform.reaction(LOWER(reaction_name));

ALTER TABLE blogging_platform.comment_reaction
DROP COLUMN reaction_type;

ALTER TABLE blogging_platform.post_reaction
DROP COLUMN reaction_type;

ALTER TABLE blogging_platform.comment_reaction
ADD COLUMN reaction_id bigint NOT NULL DEFAULT 1;

ALTER TABLE blogging_platform.post_reaction
ADD COLUMN reaction_id bigint NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS blogging_platform.comment_reaction
ADD CONSTRAINT comment_reaction_reaction_fkey FOREIGN KEY (reaction_id) REFERENCES blogging_platform.reaction(reaction_id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS blogging_platform.post_reaction
ADD CONSTRAINT post_reaction_reaction_fkey FOREIGN KEY (reaction_id) REFERENCES blogging_platform.reaction(reaction_id) ON DELETE CASCADE;

INSERT INTO blogging_platform.reaction(reaction_name)
VALUES
    ('LIKE'),
    ('DISLIKE');