ALTER TABLE blogging_platform.post_reaction DROP CONSTRAINT post_reaction_pkey;
ALTER TABLE blogging_platform.comment_reaction DROP CONSTRAINT comment_reaction_pkey;

ALTER TABLE blogging_platform.post_reaction ADD COLUMN post_reaction_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE blogging_platform.comment_reaction ADD COLUMN comment_reaction_id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE IF EXISTS blogging_platform.post_reaction
ADD CONSTRAINT post_reaction_pkey PRIMARY KEY (post_reaction_id);

ALTER TABLE IF EXISTS blogging_platform.comment_reaction
ADD CONSTRAINT comment_reaction_pkey PRIMARY KEY (comment_reaction_id);