CREATE TABLE IF NOT EXISTS blogging_platform.user (
    user_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    login      text UNIQUE NOT NULL,
    password   text        NOT NULL,
    email      text UNIQUE NOT NULL,
    created_at timestamptz NOT NULL,
    last_login timestamptz
);

ALTER TABLE IF EXISTS blogging_platform.user
ADD CONSTRAINT user_pk PRIMARY KEY (user_id);