CREATE TABLE IF NOT EXISTS blogging_platform.user (
    user_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    login      varchar(50) UNIQUE  NOT NULL,
    password   varchar(50)         NOT NULL,
    email      varchar(255) UNIQUE NOT NULL,
    created_at timestamptz         NOT NULL,
    last_login timestamptz
);

ALTER TABLE IF EXISTS blogging_platform.user
ADD CONSTRAINT user_pk PRIMARY KEY (user_id);