CREATE TABLE IF NOT EXISTS blogging_platform.role (
    role_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    role_name text NOT NULL UNIQUE
);

ALTER TABLE IF EXISTS blogging_platform.role
ADD CONSTRAINT role_pk PRIMARY KEY (role_id);