CREATE TABLE IF NOT EXISTS blogging_platform.tag (
    tag_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    tag_name text NOT NULL UNIQUE
);

ALTER TABLE IF EXISTS blogging_platform.tag
ADD CONSTRAINT tag_pk PRIMARY KEY (tag_id);